# Generated by Django 5.2.17 on 2026-09-19 15:42

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('risk_level', models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_proposals', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_proposals', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Proposta de compra',
                'verbose_name_plural': 'Propostas de compra',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_proposal_quantity_gt_0'), models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='purchase_proposal_unit_price_gt_0'), models.CheckConstraint(condition=models.Q(('total_price__gt', 0)), name='purchase_proposal_total_price_gt_0'), models.CheckConstraint(condition=models.Q(('total_price', django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price')))), name='purchase_proposal_total_matches'), models.CheckConstraint(condition=models.Q(('status__in', ('PENDING', 'APPROVED', 'REJECTED'))), name='purchase_proposal_valid_status'), models.CheckConstraint(condition=models.Q(('risk_level__in', ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW'))), name='purchase_proposal_valid_risk'), models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('status', 'PENDING')), models.Q(('reviewed_at__isnull', False), ('status__in', ('APPROVED', 'REJECTED'))), _connector='OR'), name='purchase_proposal_review_state')],
            },
        ),
    ]
