# Generated by Django 5.2.17 on 2026-09-19 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseproposal',
            options={'ordering': ['-created_at', '-pk'], 'permissions': [('review_purchaseproposal', 'Can review purchase proposals')], 'verbose_name': 'Proposta de compra', 'verbose_name_plural': 'Propostas de compra'},
        ),
        migrations.RemoveConstraint(
            model_name='purchaseproposal',
            name='purchase_proposal_review_state',
        ),
        migrations.AddField(
            model_name='purchaseproposal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_purchase_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='purchaseproposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('status', 'PENDING')), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False), ('status__in', ('APPROVED', 'REJECTED'))), _connector='OR'), name='purchase_proposal_review_state'),
        ),
    ]
