# Generated by Django 5.2.17 on 2026-09-19 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('LIMIT_REACHED', 'LIMIT_REACHED')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user_request', models.TextField()),
                ('final_response', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
                'permissions': [('execute_agent_write', 'Can execute Agent write tools')],
            },
        ),
        migrations.CreateModel(
            name='AgentToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=150)),
                ('tool_call_id', models.CharField(max_length=255)),
                ('permission_level', models.CharField(blank=True, choices=[('READ', 'READ'), ('COMPUTE', 'COMPUTE'), ('WRITE', 'WRITE'), ('CRITICAL', 'CRITICAL')], max_length=10)),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('EXECUTED', 'EXECUTED'), ('BLOCKED', 'BLOCKED'), ('FAILED', 'FAILED')], default='RUNNING', max_length=10)),
                ('arguments', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='agent.agentexecution')),
            ],
            options={
                'ordering': ('started_at', 'pk'),
            },
        ),
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(fields=['status', '-started_at'], name='agent_exec_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttoolexecution',
            index=models.Index(fields=['status', '-started_at'], name='agent_tool_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='agenttoolexecution',
            constraint=models.UniqueConstraint(fields=('execution', 'tool_call_id'), name='agent_tool_execution_call_unique'),
        ),
    ]
