# Generated by Django 5.2.17 on 2026-09-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agentexecution",
            options={
                "ordering": ("-started_at",),
                "permissions": [
                    ("execute_agent_write", "Can execute Agent write tools"),
                    ("configure_ai", "Can view and configure AI settings"),
                ],
            },
        ),
    ]
