# Generated by Django 5.2.17 on 2026-09-21 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_agentexecution_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('LOCAL', 'Local'), ('CLOUD', 'Nuvem')], max_length=5)),
                ('integration', models.CharField(choices=[('ollama', 'Ollama'), ('mistral', 'Mistral')], max_length=20)),
                ('model', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='agent_ai_singleton'), models.CheckConstraint(condition=models.Q(models.Q(('integration', 'ollama'), ('type', 'LOCAL')), models.Q(('integration', 'mistral'), ('type', 'CLOUD')), _connector='OR'), name='agent_ai_supported_pair')],
            },
        ),
        migrations.CreateModel(
            name='AIConfigurationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('integration', models.CharField(max_length=20)),
                ('is_active', models.BooleanField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-changed_at', '-pk'),
            },
        ),
    ]
