# Generated by Django 5.2.17 on 2026-09-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_aiconfiguration_aiconfigurationchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfiguration',
            name='local_endpoint',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
