# Generated by Django 5.2.17 on 2026-09-19 15:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'ordering': ['product__name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('current_quantity__gte', 0)), name='inventory_current_quantity_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saida')], max_length=3)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product')),
            ],
            options={
                'verbose_name': 'Movimentacao de estoque',
                'verbose_name_plural': 'Movimentacoes de estoque',
                'ordering': ['-occurred_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_movement_quantity_gt_0'), models.CheckConstraint(condition=models.Q(('type__in', ('IN', 'OUT'))), name='stock_movement_valid_type')],
            },
        ),
    ]
